
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.PrintStream;

public class ChatApp extends JFrame {
    private JPanel mainPanel;
    private JTextField hostTextField;
    private JTextField portTextField;
    private JLabel portLabel;
    private JLabel hostLabel;
    public JButton connectButton;
    private JLabel aliasLabel;
    private JTextField aliasTextField;
    private JScrollPane outputScrollPane;
    private JTextArea chatTextArea;
    public JButton sendMessageButton;
    public JButton startServerButton;
    public JButton disconnectButton;
    private JTextField messageTextArea;
    private JLabel messageLabel;
    private JLabel chatAreaLabel;
    private Client client;

    public ChatApp(Client c) {
        System.setOut(new PrintStream(new TextAreaOutputStream(chatTextArea)));
        client = c;
        aliasTextField.setText(client.getAlias());

        startServerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String result = connectToServer(hostTextField.getText(), portTextField.getText());
                if (result.length() > 0) {
                    System.out.println(result);
                }
            }
        });
        disconnectButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String result = disconnectFromServer();
                if (result.length() > 0) {
                    System.out.println(result);
                }
            }
        });
        sendMessageButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String result = sendMessageToServer("");
                if (result.length() > 0) {
                    System.out.println(result);
                }
            }
        });
        startServerButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String result = startServer();
                if (result.length() > 0) {
                    System.out.println(result);
                }
            }
        });
    }

    public String connectToServer(String hostName, String portNumber) {
        return null;
    }

    public String disconnectFromServer() {
        return null;
    }

    public String sendMessageToServer(String MessageText) {
        return null;
    }

    public String startServer() {
        return null;
    }

    public static void main(String[] args) {
        setTheme();
        ChatApp gui = new ChatApp(new Session());
        JFrame frame = new JFrame("Chat App");
        frame.setContentPane(gui.mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private static void setTheme() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception ignored) {
            // if we can't get a nice theme, run anyway
        }
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        panel1.setAutoscrolls(true);
        panel1.setPreferredSize(new Dimension(700, 400));
        mainPanel.add(panel1, BorderLayout.CENTER);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10), null));
        outputScrollPane = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 4;
        gbc.weighty = 5.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel1.add(outputScrollPane, gbc);
        chatTextArea = new JTextArea();
        chatTextArea.setEditable(false);
        chatTextArea.setEnabled(false);
        chatTextArea.setLineWrap(true);
        chatTextArea.setText("");
        outputScrollPane.setViewportView(chatTextArea);
        startServerButton = new JButton();
        startServerButton.setText("Start Server");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(startServerButton, gbc);
        disconnectButton = new JButton();
        disconnectButton.setEnabled(false);
        disconnectButton.setText("Disconnect");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(disconnectButton, gbc);
        messageTextArea = new JTextField();
        messageTextArea.setEnabled(false);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(messageTextArea, gbc);
        aliasTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 2;
        gbc.weightx = 0.25;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(aliasTextField, gbc);
        portTextField = new JTextField();
        portTextField.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 1;
        gbc.weightx = 0.25;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(portTextField, gbc);
        hostTextField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.weightx = 0.25;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(hostTextField, gbc);
        portLabel = new JLabel();
        portLabel.setText("Port: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.weightx = 0.2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel1.add(portLabel, gbc);
        aliasLabel = new JLabel();
        aliasLabel.setText("Alias: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel1.add(aliasLabel, gbc);
        connectButton = new JButton();
        connectButton.setEnabled(true);
        connectButton.setText("Connect");
        connectButton.setToolTipText("Connect to <Host> on port <Port> with the name <Alias>");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 3;
        gbc.weightx = 0.25;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(connectButton, gbc);
        hostLabel = new JLabel();
        hostLabel.setText("Host: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weightx = 0.2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(0, 5, 0, 0);
        panel1.add(hostLabel, gbc);
        sendMessageButton = new JButton();
        sendMessageButton.setEnabled(false);
        sendMessageButton.setText("Send");
        sendMessageButton.setToolTipText("Disconnect from group server and file server");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 7;
        gbc.weightx = 0.25;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        panel1.add(sendMessageButton, gbc);
        chatAreaLabel = new JLabel();
        chatAreaLabel.setText("Chat:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.SOUTHWEST;
        panel1.add(chatAreaLabel, gbc);
        messageLabel = new JLabel();
        messageLabel.setText("Message:");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(messageLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
